In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [2]:
# load the iris dataset
iris = load_iris() 

In [3]:
# print keys of dataset
print("Keys:", iris.keys()) 

Keys: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [4]:
# print shape of the data and the target
print("Data shape", iris.data.shape) 
print("Target shape", iris.target.shape) 

Data shape (150, 4)
Target shape (150,)


In [5]:
# print 10 first elements 
print("data:", iris.data[:10]) 

data: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [6]:
# print the unique targets
print("Unique targets:", np.unique(iris.target)) 

Unique targets: [0 1 2]


In [7]:
# print the size of each target
print("Bin counts for targets:", np.bincount(iris.target))

Bin counts for targets: [50 50 50]


In [8]:
# print feature and target names
print("Feature names:", iris.feature_names)
print("Target names:", iris.target_names)

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [ ]:
# DESCR gives us details of the data set:
print(irisData["DESCR"])